# Generated by Django 4.2.4 on 2023-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_price_alter_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(blank=True, max_length=16, null=True, verbose_name='номер карты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvc',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='cvc код'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_month',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='месяц срока карты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='год срока карты'),
        ),
    ]
