# Generated by Django 4.2.4 on 2023-09-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_card_number_payment_cvc_payment_exp_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, null=True, verbose_name='id оплаты'),
        ),
    ]
