# Generated by Django 4.2.4 on 2023-09-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер карты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.IntegerField(blank=True, null=True, verbose_name='cvc код'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='месяц срока карты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='год срока карты'),
        ),
    ]
