# Generated by Django 4.2.4 on 2023-09-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_payment_card_number_alter_payment_cvc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
